In [4]:
# Addition of two matrices using arrays.

matrix1 = [
    [1, 2, 3],
    [4, 5, 6]
]

matrix2 = [
    [7, 8, 9],
    [10, 11, 12]
]

result = [
    [0, 0, 0],
    [0, 0, 0]
]

for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] + matrix2[i][j]

print ("Matrix 1:")
for row in matrix1:
    print (row)

print ("\nMatrix 2:")
for row in matrix2:
    print (row)

print ("\nSum of Matrix 1 and Matrix 2:") 
for row in result:
    print (row)

Matrix 1:
[1, 2, 3]
[4, 5, 6]

Matrix 2:
[7, 8, 9]
[10, 11, 12]

Sum of Matrix 1 and Matrix 2:
[8, 10, 12]
[14, 16, 18]


In [7]:
# Addition of two arrays using Numpy library.
import numpy
arr1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = numpy.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
result = arr1 + arr2
print (result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
